Update objective-c-xcode.yml
If without `-sdk iphonesimulator`, then build failed, because try to code signing.

```
error: No profiles for 'io.github.ykws.ObjcQrExample' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'io.github.ykws.ObjcQrExample'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'ObjcQrExample' from project 'ObjcQrExample')
```